const Colors = [
  { name: 'IndianRed', hex: 'CD5C5C' },
  { name: 'LightCoral', hex: 'F08080' },
  { name: 'Salmon', hex: 'FA8072' },
  { name: 'DarkSalmon', hex: 'E9967A' },
  { name: 'LightSalmon', hex: 'FFA07A' },
  { name: 'Crimson', hex: 'DC143C' },
  { name: 'Red', hex: 'FF0000' },
  { name: 'FireBrick', hex: 'B22222' },
  { name: 'DarkRed', hex: '8B0000' },
  { name: 'Pink', hex: 'FFC0CB' },
  { name: 'LightPink', hex: 'FFB6C1' },
  { name: 'HotPink', hex: 'FF69B4' },
  { name: 'DeepPink', hex: 'FF1493' },
  { name: 'MediumVioletRed', hex: 'C71585' },
  { name: 'PaleVioletRed', hex: 'DB7093' },
  { name: 'LightSalmon', hex: 'FFA07A' },
  { name: 'Coral', hex: 'FF7F50' },
  { name: 'Tomato', hex: 'FF4500' },
  { name: 'OrangeRed', hex: 'FF8C00' },
  { name: 'DarkOrange', hex: 'FF8C00' },
  { name: 'Orange', hex: 'FFA500' },
  { name: 'Gold', hex: 'FFD700' },
  { name: 'Yellow', hex: 'FFFF00' },
  { name: 'LightYellow', hex: 'FFFFE0' },
  { name: 'LemonChiffon', hex: 'FFFACD' },
  { name: 'LightGoldenrodYellow', hex: 'FAFAD2' },
  { name: 'PapayaWhip', hex: 'FFEFD5' },
  { name: 'Moccasin', hex: 'FFE4B5' },
  { name: 'PeachPuff', hex: 'FFDAB9' },
  { name: 'PaleGoldenrod', hex: 'EEE8AA' },
  { name: 'Khaki', hex: 'F0E68C' },
  { name: 'DarkKhaki', hex: '8DB76B' },
  { name: '', hex: '' },
]

export default Colors
